[package]
name = "twitch_irc"
authors = ["Júlia Paschoalinoto <julia@juliapixel.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.13" }
log = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
# lazy_static = "1.4"
# regex = "1.7"
tungstenite = {version = "0.18", features = ["native-tls"]}

[dev-dependencies]
criterion = "0.4"
rand = "0.8"

[[bench]]
name = "benches"
harness = false

[features]
serde = ["dep:serde", "hashbrown/serde"]
